export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const EDIT_PRODUCTS = "EDIT_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
